app:
  name: 'montoredapp2'
  region: 'Polska'
  ip: 10.6.4.4

management:
  endpoints.web.exposure:
    include: '*'
    exclude: env,beans,jvm

  metrics:
    tags:
      appName: 'monitoredApp1'
  application:
    name: 'monitoredApp1'

management.metrics.export.statsd:
  enabled: 'true'
  flavor: 'telegraf'
  host: 'telegraf'
  port: 8125

spring:
  application:
    name: 'monitoredApp2'
server:
  port: 8081
