version: '3'
services:

  # https://hub.docker.com/_/influxdb
  influxdb:
    build:
      context: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ${INFLUXDB_VOLUME}:/var/lib/influxdb

  # https://hub.docker.com/_/telegraf
  telegraf:
    build:
      context: telegraf
    ports:
      - "8125:8125/udp"
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
    links:
      - influxdb
    depends_on:
      - influxdb

  kapacitor:
    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    build:
      context: kapacitor
    volumes:
      # Mount for kapacitor data directory
      - ${KAPACITOR_VOLUME}/data:/var/lib/kapacitor
      # Mount for kapacitor configuration
#      - ./kapacitor/config/:/etc/kapacitor/
    # Kapacitor requires network access to Influxdb
    links:
      - influxdb
    ports:
      - "9092:9092"
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    depends_on:
      - influxdb

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    build:
      context: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    links:
      - influxdb
      - kapacitor
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

  grafana:
    # Full tag list: https://hub.docker.com/r/grafana/grafana/
    build:
      context: grafana
      args:
        - GRAFANA_VERSION=latest
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
#     Need to fix permissions after first run: chown -R 472:472 ./
      - ${GRAFANA_VOLUME}:/var/lib/grafana
    links:
      - influxdb
    depends_on:
      - influxdb

  monitoredapp1:
    build:
      context: ../..
      dockerfile: src/docker/monitoredapp1/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default,zipkin-jdbc-trace
      - SPRING_DATASOURCE_URL=jdbc:postgresql://monitoredpostgres:5432/testDb
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_HOST=monitoredrabbitmq1
      - SPRING_RABBITMQ_VIRTUALHOST=testVHost
      - SPRING_RABBITMQ_USERNAME=testRabbitUser
      - SPRING_RABBITMQ_PASSWORD=testRabbitPassword
      - PL_CWSFE_MONITOREDAPP2_URL=http://monitoredapp2:8081
      - MANAGEMENT_METRICS_EXPORT_STARTSD_ENABLED=true
      - MANAGEMENT_METRICS_EXPORT_STARTSD_PORT=8125
      - MANAGEMENT_METRICS_EXPORT_STARTSD_FLAVOR=TELEGRAF
      - MANAGEMENT_METRICS_EXPORT_STARTSD_HOST=telegraf
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    links:
      - telegraf
      - monitoredpostgres
      - monitoredapp2
      - zipkin
    depends_on:
      - telegraf
      - monitoredpostgres
      - monitoredapp2
      - monitoredrabbitmq1
      - zipkin

  monitoredapp2:
    build:
      context: ../..
      dockerfile: src/docker/monitoredapp2/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MANAGEMENT_METRICS_EXPORT_STARTSD_ENABLED=true
      - MANAGEMENT_METRICS_EXPORT_STARTSD_PORT=8125
      - MANAGEMENT_METRICS_EXPORT_STARTSD_FLAVOR=TELEGRAF
      - MANAGEMENT_METRICS_EXPORT_STARTSD_HOST=telegraf
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_HOST=monitoredrabbitmq1
      - SPRING_RABBITMQ_VIRTUALHOST=testVHost
      - SPRING_RABBITMQ_USERNAME=testRabbitUser
      - SPRING_RABBITMQ_PASSWORD=testRabbitPassword
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
    links:
      - telegraf
      - zipkin
    depends_on:
      - monitoredrabbitmq1
      - telegraf
      - zipkin

  monitoredpostgres:
    build:
      context: ../..
      dockerfile: src/docker/monitoredPostgres/Dockerfile
    ports:
      - "5433:5432"
    environment:
    - POSTGRES_DB=testDb
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    links:
      - telegraf
    depends_on:
      - telegraf

  monitoredrabbitmq1:
    build:
      context: ../..
      dockerfile: src/docker/rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
    - RABBITMQ_NODENAME=monitoredrabbitmq1
    - RABBITMQ_DEFAULT_USER=testRabbitUser
    - RABBITMQ_DEFAULT_PASS=testRabbitPassword
    - RABBITMQ_DEFAULT_VHOST=testVHost
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq/mnesia/

  zipkin:
    build:
      context: ../..
      dockerfile: src/docker/zipkin/Dockerfile
    ports:
      - "9411:9411"
