app:
  name: 'montoredapp1'
  region: 'Polska'
  ip: 10.6.4.3

management:
  endpoints.web.exposure:
    include: '*'
    exclude: env,beans,jvm

  metrics:
    tags:
      appName: 'monitoredApp1'
  application:
    name: 'monitoredApp1'

management.metrics.export.statsd:
  enabled: 'true'
  flavor: 'telegraf'
  host: 'telegraf'
  port: 8125

spring:
  application:
    name: 'monitoredApp1'
  datasource:
    type: 'com.zaxxer.hikari.HikariDataSource'
    hikari:
      pool-name: '${spring.application.name}-pool'
      minimum-idle: 3
      maximum-pool-size: 10
  flyway:
    enabled: true

  zipkin:
    service:
      name: ${spring.application.name}
    enabled: true
    discoveryClientEnabled: false
    sender.type: web
  sleuth:
    sampler:
      probability: '0.1'
